[build-system]
requires = ["astropy, scipy"]
# build-backend = "flit_core.buildapi"

[project]
name = "emccd_qe_analysis"
authors = [{name = "Aafaque R Khan", email = "arkhan@arizona.edu"}]
dynamic = ["version", "description"]
